# Uncomment the next line to define a global platform for your project
 source 'https://git.coding.net/hging/Specs.git'
 platform :ios, '7.0'

target 'PushNotificationSDKSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
  # Pods for PushNotificationSDKSample
  pod 'AFNetworking'
  pod 'SDWebImage'
end




target 'YKHDNotificationContent' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YKHDNotificationContent

end



target 'YKHDNotificationService' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YKHDNotificationService

end
